[providers.age]
type = "age"
recipients = [
    "age17fxfxhxlneysa02y5cqcnq7qxc4wkjc05q9nfaa4gm93ug6zvvls4fwc9d",
    "age185ff9qr5cl8sjggccsymsn4cqz00ksvwxsr5nutfp5lmgy842dpqgsr0el",
    "age1h52ys62jyju8zdcwuzx9yzfsqscvhnpqxxwawmswfqar2qenwc7ss5e90x",
    "age1z9ed24whsnx5xmnnmp594qcq5r27gvpjt2gjldpplaahmhjdpphq067daa",
    "age1qlc9awypeqslw2prry4apmxw0nfhkxkq78vayha9wetmcu69epjs0f3rll",
    "age1y42we6yzweagvww3mj22jw4l0edn9d7pjwr9es2cvfmkeshy79csnq8wjj",
    "age14nalzzwh75keltwhx4gtaqyhqsena2806kn6mc27cxtyqaja25gsnyjpln",
]

[providers.bitwarden]
type = "bitwarden"

[secrets]
EXAMPLE = { provider = "bitwarden", value = "qor4toal-odee-iexi-otha-chae9aaja2jo" }
