[providers.age]
type = "age"
recipients = [
    "age14nalzzwh75keltwhx4gtaqyhqsena2806kn6mc27cxtyqaja25gsnyjpln",
]

[providers.bitwarden]
type = "bitwarden"

[secrets]
EXAMPLE = { provider = "bitwarden", value = "qor4toal-odee-iexi-otha-chae9aaja2jo" }
