# [mgr]
# show_hidden = true

[plugin]
prepend_previewers = [
	{ url = "*.md", run = "glow" },
	{ mime = "text/*", run = "bat" },
]

append_previewers = [
	{ url = "*/", run = "folder" },
	{ mime = "*", run = "bat" },
]
