---
- import_playbook: common/git_init.yaml
- import_playbook: arch/pacman.yaml
- import_playbook: arch/yay.yaml
- import_playbook: common/docker.yaml
- import_playbook: common/python.yaml
- import_playbook: client_tools/autocompletes.yaml
- import_playbook: client_tools/zsh.yaml
- import_playbook: client_tools/zen.yaml
- import_playbook: common/miscellaneous.yaml
- import_playbook: common/crypto.yaml
- import_playbook: common/tailscale.yaml
