---
- import_playbook: git.yaml
- import_playbook: pacman.yaml
- import_playbook: yay.yaml
- import_playbook: docker.yaml
- import_playbook: python.yaml
- import_playbook: autocompletes.yaml
- import_playbook: zsh.yaml
- import_playbook: zen.yaml
- import_playbook: miscellaneous.yaml
- import_playbook: crypto.yaml
- import_playbook: tailscale.yaml
