---
- hosts: localhost
  connection: local
  vars_files:
    - ./variables.yaml
  tasks:
    - name: Install global requirements
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - git
          - ghostty
          - less
          - neovim
          - python
          - python-pip
          - python-virtualenv
          - terminator
          - wget
          - zsh
    - name: Install hyprland, etc
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - blueman
          - cava
          - hyprland
          - hyprlock
          - hyprpaper
          - hyprsunset
          - network-manager-applet
          - pavucontrol
          - rofi
          - swaync
          - waybar
          - xdg-desktop-portal-hyprland
    - name: Install aesthetic helpers
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - nerd-fonts
          - gnome-themes-extra
          - gnome-tweaks
    - name: Install cli tooling
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - bat
          - dysk
          - eza
          - fd
          - fzf
          - gawk
          - git-delta
          - glow
          - graphviz
          - htop
          - jq
          - pwgen
          - sd
          - unzip
          - yazi
          - go-yq
    - name: Install xorg (for zoom mainly)
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name: xorg-server
    - name: Install other apps
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - age
          - argocd
          - aws-cli
          - bc
          - bind
          - bitwarden-cli
          - copyq
          - dbeaver
          - direnv
          - dpkg
          - github-cli
          - gparted
          - helm
          - kubectl
          - libreoffice-still
          # Extra req for uv
          - libxcrypt-compat
          - minikube
          - mise
          - ncspot
          - networkmanager-openvpn
          # - nodejs
          - nvm
          - obsidian
          - ollama
          - openvpn
          - pandoc-cli
          - pgcli
          - pulumi
          - pyenv
          - rpi-imager
          - sops
          - tk
          - tree
          - usage
          - uv
          - xclip
          - yarn
          - ydotool
    - name: Install email
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - isync
          - neomutt
    - name: Install audio
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - pipewire
          - pipewire-alsa
          - pipewire-audio
          - pipewire-pulse
          - sof-firmware
    - name: Install bluetooth
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      community.general.pacman:
        state: present
        name:
          - bluez
          - bluez-utils
    - name: Enable, start bluetooth
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      ansible.builtin.systemd_service:
        name: bluetooth.service
        state: started
        enabled: true
    - name: Enable, start time sync
      when: ansible_facts["distribution"] == "Archlinux"
      become: true
      ansible.builtin.systemd_service:
        name: systemd-timesyncd.service
        enabled: true
        state: started
    - name: Enable, start ydotool
      when: ansible_facts["distribution"] == "Archlinux"
      ansible.builtin.systemd_service:
        name: ydotool
        enabled: true
        scope: user
        state: started
